version: '3.9'
services:
  app:
    build: ./infra/python
    volumes:
      - ./src:/app
    working_dir: /app
    ports:
      - "8082:8082"
    command: gunicorn --log-level debug project.main:app
